kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service-canary
spec:
  type: LoadBalancer
  selector:
    app: train-schedule
    target: canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment-canary
  labels:
    app: train-schedule
spec:
  replicas: $CANARY_REPLICAS
  selector:
    matchLabels:
      target: canary
      app: train-schedule
  template:
    metadata:
      labels:
        target: canary
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
